  - name: Copy Linux Host Template
    template:
      src: mailServers0.cfg.j2
      dest: /usr/local/nagios/etc/hosts/{{ nagiosHost0 }}.cfg

  - name: Copy Linux Host Template
    template:
      src: mailServers1.cfg.j2
      dest: /usr/local/nagios/etc/hosts/{{ nagiosHost1 }}.cfg

  - name: Restart nagios
    service:
       name: nagios
       state: restarted