  - name: Prerequisites Install
    apt:
      name:
        - autoconf
        - gcc 
        - libc6
        - make
        - wget
        - unzip
        - apache2
        - php
        - libapache2-mod-php7.2
        - libgd-dev
        - python-pip

  - pip:
      name:
       - passlib

  - name: Downlaod
    get_url:
      url: https://github.com/NagiosEnterprises/nagioscore/archive/nagios-4.4.6.tar.gz
      dest: /tmp/nagioscore-4.4.6.tar.gz
   
  - name: Configure
    script:
       cmd: '{{ baseDirectory }}roles/nagiosServers/bashScripts/installNagiosCore/configure.sh'

  - name: Make All
    make:
      chdir: /tmp/nagioscore-nagios-4.4.6/
      target: all

  - name: Make group-users
    make:
      chdir: /tmp/nagioscore-nagios-4.4.6/
      target: install-groups-users
    
  - name: Usermod
    raw:  usermod -a -G nagios www-data

  - name: Make install
    make:
      chdir: /tmp/nagioscore-nagios-4.4.6/
      target: install

  - name: Make install-daemoninit       
    make:
      chdir: /tmp/nagioscore-nagios-4.4.6/
      target: install-daemoninit

  - name: Make install       
    make:
      chdir: /tmp/nagioscore-nagios-4.4.6/
      target: install-commandmode

  - name: Make install-config 
    make:
      chdir: /tmp/nagioscore-nagios-4.4.6/
      target: install-config

  - name: Make install-webconf
    make:
      chdir: /tmp/nagioscore-nagios-4.4.6/
      target: install-webconf

  - apache2_module:
      state: present
      name: rewrite

  - apache2_module:
      state: present
      name: cgi

  - ufw:
      rule: allow
      name: Apache

  - name: Restart Apache2
    service:
      name: apache2
      state: restarted

  - htpasswd:
      path: /usr/local/nagios/etc/htpasswd.users
      name: nagiosadmin
      password: '{{ nagiosadmin_pass }}'

  - name: Start Web UI
    service:
     name: nagios
     state: started

  - name: Start Nagios
    service:
     name: nagios
     state: started

  - name: Stop Nagios
    service:
     name: nagios
     state: stopped

  - name: Restart Nagios
    service:
     name: nagios
     state: reloaded


  - name: Copy Nagios Config Template
    template:
      src: nagios.cfg.j2
      dest: /usr/local/nagios/etc/nagios.cfg

  - name: Create /hosts directory
    file:
      path: /usr/local/nagios/etc/hosts
      state: directory
    notify: chown /host to nagios

  - name: Copy Linux Host Template
    template:
      src: linux.cfg.j2
      dest: /usr/local/nagios/etc/objects/linux.cfg
