  - name: Update and Upgrade
    apt:
      upgrade: yes
      update_cache: yes
      cache_valid_time: 86400

  - name: Prerequisites Install
    apt:
      name:
        - autoconf
        - gcc 
        - libc6
        - make
        - wget
        - unzip
        - apache2
        - php
        - libapache2-mod-php7.2
        - libgd-dev
        - python-pip

  - pip:
      name:
       - passlib

  - name: Downlaod Nagios Core
    get_url:
      url: https://github.com/NagiosEnterprises/nagioscore/archive/nagios-4.4.6.tar.gz
      dest: /tmp/nagioscore-4.4.6.tar.gz
   
  - name: Unpack Nagios Core
    raw: cd /tmp && tar xzf nagioscore-4.4.6.tar.gz
#    unarchive:
#      src: /tmp/nagioscore-4.4.6.tar.gz
#      des: /tmp/nagioscore-4.4.6

  - name: Configure
    raw: cd /tmp/nagioscore-nagios-4.4.6/ && ./configure --with-httpd-conf=/etc/apache2/sites-enabled

  - name: Make All
    make:
      chdir: /tmp/nagioscore-nagios-4.4.6/
      target: all

  - name: Make group-users
    make:
      chdir: /tmp/nagioscore-nagios-4.4.6/
      target: install-groups-users
    
  - name: Usermod
    raw:  usermod -a -G nagios www-data

  - name: Make install
    make:
      chdir: /tmp/nagioscore-nagios-4.4.6/
      target: install

  - name: Make install-daemoninit       
    make:
      chdir: /tmp/nagioscore-nagios-4.4.6/
      target: install-daemoninit

  - name: Make install       
    make:
      chdir: /tmp/nagioscore-nagios-4.4.6/
      target: install-commandmode

  - name: Make install-config 
    make:
      chdir: /tmp/nagioscore-nagios-4.4.6/
      target: install-config

  - name: Make install-webconf
    make:
      chdir: /tmp/nagioscore-nagios-4.4.6/
      target: install-webconf

  - apache2_module:
      state: present
      name: rewrite

  - apache2_module:
      state: present
      name: cgi

  - ufw:
      rule: allow
      name: Apache

  - name: Restart Apache2
    service:
      name: apache2
      state: restarted

  - htpasswd:
      path: /usr/local/nagios/etc/htpasswd.users
      name: nagiosadmin
      password: systems

  - name: Start Web UI
    service:
     name: nagios
     state: started

  - name: Start Nagios
    service:
     name: nagios
     state: started

  - name: Stop Nagios
    service:
     name: nagios
     state: stopped

  - name: Restart Nagios
    service:
     name: nagios
     state: reloaded

  - name: Create /hosts directory
    file:
      path: /usr/local/nagios/etc/hosts
      state: directory
    notify: chown /host to nagios
    notify: Copy Nagios Config Template
    notify: Copy Linux Host Template
