---

  - name: Update and Upgrade
    apt:
      upgrade: yes
      update_cache: yes
      cache_valid_time: 86400

  - name: Prerequisites Install
    apt:
      name:
        - autoconf
        - gcc 
        - libc6
        - make
        - wget
        - unzip
        - apache2
        - php
        - libapache2-mod-php7.2
        - libgd-dev
        - python-pip

  - pip:
      name:
       - passlib

  - name: Downlaod Nagios Core
    get_url:
      url: https://github.com/NagiosEnterprises/nagioscore/archive/nagios-4.4.6.tar.gz
      dest: /tmp/nagioscore-4.4.6.tar.gz
    notify: Unpack Nagios Core

  - name: Configure
    raw: cd /tmp/nagioscore-nagios-4.4.6/ && ./configure --with-httpd-conf=/etc/apache2/sites-enabled

  - name: Make All
    make:
      chdir: /tmp/nagioscore-nagios-4.4.6/
      target: all

  - name: Make group-users
    make:
      chdir: /tmp/nagioscore-nagios-4.4.6/
      target: install-groups-users
    
  - name: Usermod
    raw:  usermod -a -G nagios www-data

  - name: Make install
    make:
      chdir: /tmp/nagioscore-nagios-4.4.6/
      target: install

  - name: Make install-daemoninit       
    make:
      chdir: /tmp/nagioscore-nagios-4.4.6/
      target: install-daemoninit

  - name: Make install       
    make:
      chdir: /tmp/nagioscore-nagios-4.4.6/
      target: install-commandmode

  - name: Make install-config 
    make:
      chdir: /tmp/nagioscore-nagios-4.4.6/
      target: install-config

  - name: Make install-webconf
    make:
      chdir: /tmp/nagioscore-nagios-4.4.6/
      target: install-webconf

  - apache2_module:
      state: present
      name: rewrite

  - apache2_module:
      state: present
      name: cgi

  - ufw:
      rule: allow
      name: Apache

  - name: Restart Apache2
    service:
      name: apache2
      state: restarted

  - htpasswd:
      path: /usr/local/nagios/etc/htpasswd.users
      name: nagiosadmin
      password: systems

  - name: Start Web UI
    service:
     name: nagios
     state: started

#Install Nagios Plugins

  - name: Prerequisites Install
    apt:
     name:
       - autoconf
       - gcc
       - libc6
       - make 
       - wget 
       - libmcrypt-dev
       - libssl-dev
       - bc
       - dc
       - build-essential
       - snmp
       - libnet-snmp-perl
       - gettext

  - name: Source Download
    raw: cd /tmp && wget --no-check-certificate -O nagios-plugins.tar.gz https://github.com/nagios-plugins/nagios-plugins/archive/release-2.2.1.tar.gz && tar zxf nagios-plugins.tar.gz

  - name: Configure
    raw: cd /tmp/nagios-plugins-release-2.2.1/ && ./tools/setup && ./configure

  - name: Make
    make:
      chdir: /tmp/nagios-plugins-release-2.2.1/

  - name: Make Install
    make:
      chdir: /tmp/nagios-plugins-release-2.2.1/
      target: install

#------------------------

  - name: Start Nagios
    service:
     name: nagios
     state: started

  - name: Stop Nagios
    service:
     name: nagios
     state: stopped

  - name: Restart Nagios
    service:
     name: nagios
     state: reloaded

  - name: Create /hosts directory
    file:
      path: /usr/local/nagios/etc/hosts
      state: directory

  - name: chown /host to nagios
    file:
      path: /usr/local/nagios/etc/hosts
      owner: nagios
      group: nagios

  - name: Copy Nagios Config Template
    template:
      src: nagios.cfg.j2
      dest: /usr/local/nagios/etc/nagios.cfg

  - name: Copy Linux Host Template
    template:
      src: linux.cfg.j2
      dest: /usr/local/nagios/etc/objects/linux.cfg
