   - name: Install Prerequisites
     apt:
       name:
        - autoconf
        - automake
        - gcc
        - libc6
        - libmcrypt-dev
        - make
        - libssl-dev
        - wget
        - openssl

   - name: Source Download
     get_url:
       url: https://github.com/NagiosEnterprises/nrpe/archive/nrpe-3.2.1.tar.gz
       dest: /tmp/nrpe.tar.gz

   - name: Configure
     script:
       cmd: '{{ role_path }}/bashScripts/installNRPE/configure.sh'

   - name: Make
     make:
       chdir: /tmp/nrpe-nrpe-3.2.1/
       target: all

   - name: Make install-group-users
     make:
       chdir: /tmp/nrpe-nrpe-3.2.1/
       target: install-groups-users

   - name: Make install
     make:
       chdir: /tmp/nrpe-nrpe-3.2.1/
       target: install

   - name: Make install-config
     make:
       chdir: /tmp/nrpe-nrpe-3.2.1/
       target: install-config

   - name: Update /etc/services
     script:
       cmd: '{{ role_path }}/bashScripts/installNRPE/updateServices.sh'

   - name: Make install-init
     make:
       chdir: /tmp/nrpe-nrpe-3.2.1/
       target: install-init

   - name: Enable nrpe
     service:
       name: nrpe
       service: enable

   - name: Create /etc/ufw/applications.d directory
     file:
       path: /etc/ufw/applications.d
       state: directory

   - name: Edit ufw config
     script:
       cmd: '{{ role_path }}/bashScripts/installNRPE/ufwConfig.sh'

   - ufw:
       rule: allow
       name: NRPE

   - name: Copy nrpe Template
     template:
      src: nrpe.cfg.j2
      dest: /usr/local/nagios/etc/nrpe.cfg

   - name: Start nrpe
     service:
       name: nrpe
       state: started
