  - name: Prerequisites Install
    apt:
     name:
       - autoconf
       - gcc
       - libc6
       - make 
       - wget 
       - libmcrypt-dev
       - libssl-dev
       - bc
       - dc
       - build-essential
       - snmp
       - libnet-snmp-perl
       - gettext

  - name: Source Download
    get_url:
      url: https://github.com/nagios-plugins/nagios-plugins/archive/release-2.2.1.tar.gz
      dest: /tmp/nagios-plugins.tar.gz

  - name: Source Download and Configure
    script:
       cmd: {{ baseDirectory }}roles/mailServers/bashScripts/installNagiosPlugins/configure.sh

  - name: Make
    make:
      chdir: /tmp/nagios-plugins-release-2.2.1/

  - name: Make Install
    make:
      chdir: /tmp/nagios-plugins-release-2.2.1/
      target: install
