#Add host file to the Nagios servers and restart the service
---
- hosts: servers
  vars:
   host: ""
   ip: ""
  become: yes
 
  tasks: 
   - name: "Create host config file"
     command: cp /usr/local/nagios/etc/objects/linux.cfg /usr/local/nagios/etc/hosts/{{ host }}.cfg
 
   - name: "Mend config host"
     replace:
        path: /usr/local/nagios/etc/hosts/{{ host }}.cfg
        regexp: 'linux'
        replace: '{{ host }}'
 
   - name: "Mend config IP"
     replace:
       path: /usr/local/nagios/etc/hosts/{{ host }}.cfg
       regexp: '128.82.6.x'
       replace: '{{ ip }}'
 
   - name: "Restart nagios"
     service:
        name: nagios
        state: restarted
