#Configure hosts to be deployed into use using standards of the department

---
- hosts: clients
  become: yes
  tasks:
#Define DNS servers

  - name: Copy Netplan Template
    copy:
      src: /home/carson/ansiblePlays/templates/01-netcfg.yaml
      dest: /etc/netplan/01-netcfg.yaml

  - name: Mend Netplan config
    replace:
      path: /etc/netplan/01-netcfg.yaml
      regexp: '128.82.6.x'
      replace: '{{ ansible_default_ipv4.address }}'

  - name: Apply Netplan
    raw: netplan apply 

#UCarp

  - name: Ucarp Install
    apt:
      name:
       - ucarp

  - name: Copy vip-up template
    copy:
      src: /home/carson/ansiblePlays/templates/vip-up
      dest: /usr/share/ucarp/vip-up

  - name: Copy vip-down template
    copy:
      src: /home/carson/ansiblePlays/templates/vip-down
      dest: /usr/share/ucarp/vip-down

  - name: Configure Ucarp
    raw: /usr/sbin/ucarp --interface=ens160 --pass=systems --srcip=128.82.6.20 --vhid=1 --addr=128.82.6.172 --shutdown --preempt --advskew=0 --upscript=/usr/share/ucarp/vip-up --downscript=/usr/share/ucarp/vip-down

#  - name: Mend ucarp.service config
#    replace:
#      path: /usr/sbin/ucarp
#      regexp: '128.82.6.20'
#      replace: '{{ ansible_default_ipv4.address }}'

  - name: Copy ucarp.service template
    copy:
      src: /home/carson/ansiblePlays/templates/ucarp.service
      dest: /usr/share/ucarp/ucarp.service

  - name: Mend ucarp.service config
    replace:
      path: /usr/share/ucarp/ucarp.service
      regexp: '128.82.6.x'
      replace: '{{ ansible_default_ipv4.address }}'

#  - name: Enable Ucarp
#    service:
#      name: ucarp
#      state: enabled

#MOTD
  - name: Copy MOTD Template
    copy:
       src: /home/carson/ansiblePlays/templates/motd
       dest: /etc/motd

  - name: "Mend MOTD config"
    replace:
      path: /etc/motd
      regexp: '128.82.6.x'
      replace: '{{ ansible_default_ipv4.address }}'

#Monitoring

  - include: installNRPE.yml
  
  - include: installNagiosPlugins.yml

#Postfix

  - name: Install Postfix
    apt:
      name:
        - postfix

  - name: Copy main.cf Template
    copy:
       src: /home/carson/ansiblePlays/templates/main.cf
       dest: /etc/postfix/main.cf

  - name: "Mend MOTD config"
    replace:
      path: /etc/postfix/main.cf
      regexp: 'x.cj.undernet.cs.odu.edu'
      replace: '{{ ansible_hostname }}.cj.undernet.cs.odu.edu'

  - name: Restart Postfix
    service:
     name: postfix
     state: reloaded

  - ufw:
       rule: allow
       name: postfix